output:
	gcc -Wall -Wextra -Werror -pedantic -g 1-main.c 1-binary.c -o 1-binary
	gcc -Wall -Wextra -Werror -pedantic -g 100-main.c 100-jump.c -lm -o 100-jump
	gcc -Wall -Wextra -Werror -pedantic -g 104-main.c 104-advanced_binary.c -o 104-advanced_binary
